### ISSUE TITLE
rake task fails if converted description surpasses database limit

### ISSUE THREAD

**Issue by Hnasar** [Ecodev/redmine_convert_textile_to_markown#7]
I ran the usual 

`bundle exec rake convert_textile_to_markdown RAILS_ENV=production`

but it failed halfway through because I had an issue whose description was 65535 bytes long (the limit of a text column in mariadb).

It'd be nice if the code handled the error and skipped the issue.
We worked around it by truncating all issues which were at the limit.

Thanks for the cool tool!

**Comment by PowerKiKi** [comment]
I am not sure what would be the best. Truncating the text would be a loss of data, which is IMHO not  really acceptable. Skipping the conversion would not really be ideal either. I'd say that crashing might be the less bad option of all. So that the user can take proper manual step to fix it, like you did.

**Comment by PowerKiKi** [comment]
Closing as wontfix, because crashing still seems to be the best option.
